/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio003;

/**
 *
 * @author l84119663
 */
public class Ejercicio003 extends javax.swing.JFrame {

    public Ejercicio003() {
        initComponents();
        rbtComodin.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rdbCombo1 = new javax.swing.JRadioButton();
        rbdCombo2 = new javax.swing.JRadioButton();
        rbdCombo3 = new javax.swing.JRadioButton();
        rbdOpciones = new javax.swing.JRadioButton();
        rbtComodin = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtRecibido = new javax.swing.JTextField();
        txtCambio = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtHamburguesa = new javax.swing.JTextField();
        txtPapas = new javax.swing.JTextField();
        txtRefresco = new javax.swing.JTextField();
        txtPizza = new javax.swing.JTextField();
        txtGaseosa = new javax.swing.JTextField();
        txtEnsalada = new javax.swing.JTextField();
        txtYogurt = new javax.swing.JTextField();
        txtAgua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        btnCalculaPago = new javax.swing.JButton();
        btnCalculaCambio = new javax.swing.JButton();
        btnNuevaVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("PIZZERIA SALVADORENA");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Combos"));

        buttonGroup1.add(rdbCombo1);
        rdbCombo1.setText("Hamburguesa, papas, refresco");
        rdbCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCombo1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbdCombo2);
        rbdCombo2.setText("Pizza, gaseosa");
        rbdCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdCombo2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbdCombo3);
        rbdCombo3.setText("Ensalada, yogurt y agua");
        rbdCombo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdCombo3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbdOpciones);
        rbdOpciones.setText("Otras opciones");
        rbdOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdOpcionesActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtComodin);
        rbtComodin.setText("comodin");
        rbtComodin.setEnabled(false);
        rbtComodin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtComodinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbdCombo2)
                    .addComponent(rbdCombo3)
                    .addComponent(rbdOpciones)
                    .addComponent(rdbCombo1)
                    .addComponent(rbtComodin))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtComodin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addComponent(rdbCombo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbdCombo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbdCombo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbdOpciones))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagos"));

        jLabel11.setText("Total");

        jLabel12.setText("Recibido");

        jLabel13.setText("Cambio");

        txtTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        txtRecibido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCambio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCambio, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(txtRecibido)
                    .addComponent(txtTotal))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addComponent(txtRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos"));

        txtHamburguesa.setEditable(false);
        txtHamburguesa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtHamburguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHamburguesaActionPerformed(evt);
            }
        });

        txtPapas.setEditable(false);
        txtPapas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtRefresco.setEditable(false);
        txtRefresco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPizza.setEditable(false);
        txtPizza.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtGaseosa.setEditable(false);
        txtGaseosa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtEnsalada.setEditable(false);
        txtEnsalada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtYogurt.setEditable(false);
        txtYogurt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtAgua.setEditable(false);
        txtAgua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Hamburguesa $2.50");

        jLabel3.setText("Papas $0.50");

        jLabel4.setText("Refresco $0.50");

        jLabel5.setText("Pizza $4.00");

        jLabel6.setText("Gaseosa $0.60");

        jLabel7.setText("Ensalada $3.00");

        jLabel8.setText("Yogurt $0.50");

        jLabel9.setText("Agua $0.60");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAgua, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(txtYogurt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnsalada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGaseosa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPizza, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRefresco, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHamburguesa)
                    .addComponent(txtPapas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHamburguesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPapas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRefresco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGaseosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnsalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYogurt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCliente.setText("Cliente:");
        lblCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCalculaPago.setText("Calcular Pago");
        btnCalculaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaPagoActionPerformed(evt);
            }
        });

        btnCalculaCambio.setText("Calcular Cambio");
        btnCalculaCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaCambioActionPerformed(evt);
            }
        });

        btnNuevaVenta.setText("Nueva Venta");
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblCliente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCliente))
                                .addComponent(btnNuevaVenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCalculaCambio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .addComponent(btnCalculaPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente)
                            .addComponent(txtCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalculaPago)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalculaCambio)
                .addGap(10, 10, 10)
                .addComponent(btnNuevaVenta))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCombo1ActionPerformed
        // TODO add your handling code here:
        //Ham, ref, papa
        this.txtHamburguesa.setText("1");
        this.txtRefresco.setText("1");
        this.txtPapas.setText("1");
        this.txtPizza.setText("");
        this.txtGaseosa.setText("");
        this.txtEnsalada.setText("");
        this.txtYogurt.setText("");
        this.txtAgua.setText("");
        this.txtTotal.setText("");
    }//GEN-LAST:event_rdbCombo1ActionPerformed

    private void txtHamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHamburguesaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtHamburguesaActionPerformed

    private void rbdCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdCombo2ActionPerformed
        // TODO add your handling code here:
        //pizza, gaseosa
        this.txtHamburguesa.setText("");
        this.txtRefresco.setText("");
        this.txtPapas.setText("");
        this.txtPizza.setText("1");
        this.txtGaseosa.setText("1");
        this.txtEnsalada.setText("");
        this.txtYogurt.setText("");
        this.txtAgua.setText("");
        this.txtTotal.setText("");
    }//GEN-LAST:event_rbdCombo2ActionPerformed

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        // TODO add your handling code here:

        this.rdbCombo1.setSelected(false);
        this.rbdCombo2.setSelected(false);
        this.rbdCombo3.setSelected(false);
        this.rbdOpciones.setSelected(false);
        this.rbtComodin.setSelected(true);

        this.txtYogurt.setText("");
        this.txtAgua.setText("");
        this.txtEnsalada.setText("");
        this.txtGaseosa.setText("");
        this.txtHamburguesa.setText("");
        this.txtPapas.setText("");
        this.txtPizza.setText("");
        this.txtRefresco.setText("");
        this.txtTotal.setText("");
        this.txtRecibido.setText("");
        this.txtCambio.setText("");
        this.txtCliente.setText("");

        this.txtYogurt.setEditable(false);
        this.txtAgua.setEditable(false);
        this.txtEnsalada.setEditable(false);
        this.txtGaseosa.setEditable(false);
        this.txtHamburguesa.setEditable(false);
        this.txtPapas.setEditable(false);
        this.txtPizza.setEditable(false);
        this.txtRefresco.setEditable(false);


    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void rbdOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdOpcionesActionPerformed
        // TODO add your handling code here:
        this.txtYogurt.setText("");
        this.txtAgua.setText("");
        this.txtEnsalada.setText("");
        this.txtGaseosa.setText("");
        this.txtHamburguesa.setText("");
        this.txtPapas.setText("");
        this.txtPizza.setText("");
        this.txtRefresco.setText("");
        this.txtTotal.setText("");

        this.txtYogurt.setEditable(true);
        this.txtAgua.setEditable(true);
        this.txtEnsalada.setEditable(true);
        this.txtGaseosa.setEditable(true);
        this.txtHamburguesa.setEditable(true);
        this.txtPapas.setEditable(true);
        this.txtPizza.setEditable(true);
        this.txtRefresco.setEditable(true);
    }//GEN-LAST:event_rbdOpcionesActionPerformed

    private void rbtComodinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtComodinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtComodinActionPerformed

    private void rbdCombo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdCombo3ActionPerformed
        // TODO add your handling code here:
        //ensalada, yogurt, agua
        this.txtHamburguesa.setText("");
        this.txtRefresco.setText("");
        this.txtPapas.setText("");
        this.txtPizza.setText("");
        this.txtGaseosa.setText("");
        this.txtEnsalada.setText("1");
        this.txtYogurt.setText("1");
        this.txtAgua.setText("1");
        this.txtTotal.setText("");
    }//GEN-LAST:event_rbdCombo3ActionPerformed

    private void btnCalculaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaPagoActionPerformed
        // TODO add your handling code here:
        Ejercicio003ClassMetodos e03cm = new Ejercicio003ClassMetodos();

        if (this.rdbCombo1.isSelected()) {
            e03cm.setNum1(Double.parseDouble(this.txtHamburguesa.getText()));
            e03cm.setNum1(Double.parseDouble(this.txtRefresco.getText()));
            e03cm.setNum1(Double.parseDouble(this.txtPapas.getText()));
            this.txtTotal.setText(String.valueOf(e03cm.calcularCombo1()));
        } else if (this.rbdCombo2.isSelected()) {
            e03cm.setNum1(Double.parseDouble(this.txtPizza.getText()));
            e03cm.setNum1(Double.parseDouble(this.txtGaseosa.getText()));
            this.txtTotal.setText(String.valueOf(e03cm.calcularCombo2()));
        } else if (this.rbdCombo3.isSelected()) {
            e03cm.setNum1(Double.parseDouble(this.txtAgua.getText()));
            e03cm.setNum1(Double.parseDouble(this.txtEnsalada.getText()));
            e03cm.setNum1(Double.parseDouble(this.txtYogurt.getText()));
            this.txtTotal.setText(String.valueOf(e03cm.calcularCombo3()));
        }
        if (this.rbdOpciones.isSelected()) {       
       
            if(txtHamburguesa == null){
                txtHamburguesa.setText("1");
            }else if(txtAgua == null){
                txtAgua.setText("1");
            }
                
           // e03cm.setNum1(Double.parseDouble(this.txtAgua.getText()==null ? 0 :  this.txtAgua.getText()));
            
            e03cm.setNum1((this.txtHamburguesa.getText() ==null ? 0 : Double.parseDouble(this.txtHamburguesa.getText())));
            e03cm.setNum1((this.txtAgua.getText()==null ? 0 : Double.parseDouble(this.txtAgua.getText())));
            e03cm.setNum1((this.txtEnsalada.getText()==null ? 0 : Double.parseDouble(this.txtEnsalada.getText())));
            e03cm.setNum1((this.txtGaseosa.getText()==null ? 0 : Double.parseDouble(this.txtGaseosa.getText())));
            e03cm.setNum1((this.txtPapas.getText()==null ? 0 : Double.parseDouble(this.txtPapas.getText())));
            e03cm.setNum1((this.txtPizza.getText()==null ? 0 : Double.parseDouble(this.txtPizza.getText())));
            e03cm.setNum1((this.txtRefresco.getText()==null ? 0 : Double.parseDouble(this.txtRefresco.getText())));
            e03cm.setNum1((this.txtYogurt.getText()==null ? 0 : Double.parseDouble(this.txtYogurt.getText())));
            this.txtTotal.setText(String.valueOf(e03cm.calcularOtrasOpciones()));

        }

    }//GEN-LAST:event_btnCalculaPagoActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnCalculaCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaCambioActionPerformed
        // TODO add your handling code here:
        Ejercicio003ClassMetodos e03cm = new Ejercicio003ClassMetodos();

        e03cm.setNum1(Double.parseDouble(this.txtRecibido.getText()));
        e03cm.setNum2(Double.parseDouble(this.txtTotal.getText()));

        this.txtCambio.setText(String.valueOf(e03cm.calcularCambio()));

    }//GEN-LAST:event_btnCalculaCambioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio003.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio003().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculaCambio;
    private javax.swing.JButton btnCalculaPago;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JRadioButton rbdCombo2;
    private javax.swing.JRadioButton rbdCombo3;
    private javax.swing.JRadioButton rbdOpciones;
    private javax.swing.JRadioButton rbtComodin;
    private javax.swing.JRadioButton rdbCombo1;
    private javax.swing.JTextField txtAgua;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtEnsalada;
    private javax.swing.JTextField txtGaseosa;
    private javax.swing.JTextField txtHamburguesa;
    private javax.swing.JTextField txtPapas;
    private javax.swing.JTextField txtPizza;
    private javax.swing.JTextField txtRecibido;
    private javax.swing.JTextField txtRefresco;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtYogurt;
    // End of variables declaration//GEN-END:variables
}
