/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicios;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Mario Hernández
 */
public class Ejercicio07 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio007
     */
    public Ejercicio07() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMarca = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        cbxModelo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chkSunrof = new javax.swing.JCheckBox();
        chkStereo = new javax.swing.JCheckBox();
        chkRines = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        sldDias = new javax.swing.JSlider();
        rdoManual = new javax.swing.JRadioButton();
        rdoAutomatico = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        lblDias = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstMarca.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BMW", "TOYOTA", "NISSAN", "HYUNDAI" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstMarca.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMarcaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstMarca);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Renta de Vehiculos");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione sus preferencias");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        cbxModelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxModeloItemStateChanged(evt);
            }
        });

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        chkSunrof.setText("Sunroof");
        chkSunrof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSunrofActionPerformed(evt);
            }
        });

        chkStereo.setText("Stereo");
        chkStereo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkStereoActionPerformed(evt);
            }
        });

        chkRines.setText("Rines");
        chkRines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRinesActionPerformed(evt);
            }
        });

        jLabel5.setText("Extras");

        sldDias.setMajorTickSpacing(1);
        sldDias.setMaximum(30);
        sldDias.setMinimum(1);
        sldDias.setPaintTicks(true);
        sldDias.setSnapToTicks(true);
        sldDias.setToolTipText("");
        sldDias.setValue(1);
        sldDias.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDiasStateChanged(evt);
            }
        });

        buttonGroup1.add(rdoManual);
        rdoManual.setText("Manual");
        rdoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoManualActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoAutomatico);
        rdoAutomatico.setText("Automatica");
        rdoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAutomaticoActionPerformed(evt);
            }
        });

        jLabel6.setText("Dias de uso");

        jLabel7.setText("Tipo de transmision");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Total");

        lblDias.setText("1 Dias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 182, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoManual)
                            .addComponent(rdoAutomatico)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chkSunrof)
                                    .addComponent(jScrollPane1)
                                    .addComponent(cbxModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chkStereo)
                                    .addComponent(chkRines)
                                    .addComponent(sldDias, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(lblDias)))
                        .addGap(121, 121, 121))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCalcular))
                .addGap(19, 19, 19)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSunrof)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkStereo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkRines)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDias)
                    .addComponent(sldDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoManual)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoAutomatico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        HacerCalculos();
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void lstMarcaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMarcaValueChanged
        // TODO add your handling code here:
        int marca = lstMarca.getSelectedIndex();
        CrearListaModelos(marca);
        HacerCalculos();        
    }//GEN-LAST:event_lstMarcaValueChanged

    private void sldDiasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDiasStateChanged
        // TODO add your handling code here:
        this.lblDias.setText(String.valueOf(CalcularDias()) + " Dias");
        HacerCalculos();
    }//GEN-LAST:event_sldDiasStateChanged

    private void cbxModeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxModeloItemStateChanged
        // TODO add your handling code here:
        HacerCalculos();
    }//GEN-LAST:event_cbxModeloItemStateChanged

    private void chkSunrofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSunrofActionPerformed
        // TODO add your handling code here:
        HacerCalculos();
    }//GEN-LAST:event_chkSunrofActionPerformed

    private void chkStereoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkStereoActionPerformed
        // TODO add your handling code here:
        HacerCalculos();
    }//GEN-LAST:event_chkStereoActionPerformed

    private void chkRinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRinesActionPerformed
        // TODO add your handling code here:
        HacerCalculos();
    }//GEN-LAST:event_chkRinesActionPerformed

    private void rdoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoManualActionPerformed
        // TODO add your handling code here:
        HacerCalculos();
    }//GEN-LAST:event_rdoManualActionPerformed

    private void rdoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAutomaticoActionPerformed
        // TODO add your handling code here:
        HacerCalculos();
    }//GEN-LAST:event_rdoAutomaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio07.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio07().setVisible(true);
            }
        });
    }
    
    private void HacerCalculos(){
        int marca,modelo;
        Double total = 0.00;
        String print;
        
        marca = lstMarca.getSelectedIndex();
        total+= CalcularMarca(marca);
        
        modelo = cbxModelo.getSelectedIndex();
        total+= CalcularMarcaModelo(marca,modelo);
        
        total+= CalcularCheckbox();
        total+= CalcularRadios();
        
        total = (total * CalcularDias()) * 1.13;
        
        print = String.valueOf(total);
        txtResultado.setText(print);    
    }
    
    private void CrearListaModelos(int marca){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        
        switch (marca) {
            case 0:
                modelo.addElement("BMW 328");
                modelo.addElement("BMW 507");
                break;
            case 1:
                modelo.addElement("COROLLA");
                modelo.addElement("YARIS");
                break;
            case 2:
                modelo.addElement("SENTRA");
                modelo.addElement("VERSA");
                break;
            case 3:
                modelo.addElement("ACCENT");
                modelo.addElement("ELANTRA");
                break;
            default: 
                modelo.addElement("SELECCIONE MARCA");
                break;
        }
        this.cbxModelo.setModel(modelo);
    }
    
    private int CalcularMarca(int marca){
        int precio = 0;
        if(marca==0){
            precio = 50;
        }else if(marca==1){
            precio = 25;
        }else if(marca==2){
            precio = 20;
        }else if(marca==3){    
            precio = 18;
        }
        return precio;
    }
    
    private int CalcularMarcaModelo(int marca, int modelo){
        int precio = 0;
        if(marca==0){
            if(modelo==0){
                precio = 5;
            }else if(modelo==1){
                precio = 10;
            }
        }else if(marca==1){            
            if(modelo==0){
                precio = 20;
            }else if(modelo==1){
                precio = 25;
            }
        }else if(marca==2){            
            if(modelo==0){
                precio = 15;
            }else if(modelo==1){
                precio = 10;
            }
        }else if(marca==3){            
            if(modelo==0){
                precio = 10;
            }else if(modelo==1){
                precio = 15;
            }
        }
        return precio;
    }
    
    private int CalcularCheckbox(){
        int total = 0;
        if (this.chkSunrof.isSelected()) {
            total+= 10;
        }
        if (this.chkStereo.isSelected()) {
            total+= 25;
        }
        if (this.chkRines.isSelected()) {
            total+= 20;
        }        
        return total;
    }
    
    private int CalcularRadios(){
        int total = 0;
        if (this.rdoManual.isSelected()) {
            total+= 15;
        }
        if (this.rdoAutomatico.isSelected()) {
            total+= 20;
        }       
        return total;
    }
    
    private int CalcularDias(){
        int dias = sldDias.getValue();
        return dias;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxModelo;
    private javax.swing.JCheckBox chkRines;
    private javax.swing.JCheckBox chkStereo;
    private javax.swing.JCheckBox chkSunrof;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblDias;
    private javax.swing.JList<String> lstMarca;
    private javax.swing.JRadioButton rdoAutomatico;
    private javax.swing.JRadioButton rdoManual;
    private javax.swing.JSlider sldDias;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
