/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.josaphat.com.ejercicios;

import javax.swing.JOptionPane;

public class Ejercicio05 extends javax.swing.JFrame {

    public Ejercicio05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbdgSistemaOperativo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbdWindows = new javax.swing.JRadioButton();
        rbdMac = new javax.swing.JRadioButton();
        rbdLinux = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        chkOrganizado = new javax.swing.JCheckBox();
        chkAnalitico = new javax.swing.JCheckBox();
        chkProActivo = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        sldHoras = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        lblSlider = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENCUESTA");
        setResizable(false);

        jLabel1.setText("Facilitador: Salvador Peña");

        rbdgSistemaOperativo.add(rbdWindows);
        rbdWindows.setSelected(true);
        rbdWindows.setText("Windows");
        rbdWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdWindowsActionPerformed(evt);
            }
        });

        rbdgSistemaOperativo.add(rbdMac);
        rbdMac.setText("Mac");

        rbdgSistemaOperativo.add(rbdLinux);
        rbdLinux.setText("Linux");
        rbdLinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdLinuxActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecciona las habilidades que debes tener para desarrollar de forma eficiente las actividades en tu trabajo");

        chkOrganizado.setText("Organizado");

        chkAnalitico.setText("Analitico");

        chkProActivo.setText("ProActivo");

        jLabel3.setText("¿Cuantas horas pasas frente a un ordenador en tu trabajo?");

        sldHoras.setMaximum(8);
        sldHoras.setMinimum(1);
        sldHoras.setPaintLabels(true);
        sldHoras.setPaintTicks(true);
        sldHoras.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldHorasStateChanged(evt);
            }
        });

        jButton1.setText("ENVIAR ENCUESTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblSlider.setText("8 horas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkProActivo)
                    .addComponent(chkOrganizado)
                    .addComponent(jLabel3)
                    .addComponent(chkAnalitico)
                    .addComponent(jLabel2)
                    .addComponent(rbdLinux)
                    .addComponent(rbdMac)
                    .addComponent(rbdWindows)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(sldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSlider))
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(rbdWindows)
                .addGap(18, 18, 18)
                .addComponent(rbdMac)
                .addGap(18, 18, 18)
                .addComponent(rbdLinux)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(chkOrganizado)
                .addGap(18, 18, 18)
                .addComponent(chkAnalitico)
                .addGap(27, 27, 27)
                .addComponent(chkProActivo)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(sldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSlider)
                        .addGap(49, 49, 49)))
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbdWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdWindowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdWindowsActionPerformed

    private void rbdLinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdLinuxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbdLinuxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            String sistemaOperativo  ="";
            
            if(this.rbdWindows.isSelected()){
                sistemaOperativo = "Windows";
            }else if(this.rbdMac.isSelected()){
                sistemaOperativo="Mac";
            }else {
                sistemaOperativo="Linux";
            }
            
            
            String habilidades ="";
            
            if(this.chkAnalitico.isSelected()){
                habilidades="Analitico";
            }
            
            if(this.chkOrganizado.isSelected()){
                habilidades+= ( habilidades.length() > 0  ? "," :  ""  );
                habilidades+="Organizado";
            }
            
            if(this.chkProActivo.isSelected()){
                habilidades+= ( habilidades.length() > 0  ? "," :  ""  );
                habilidades+="ProActivo";
            }
            
            
            int horas = this.sldHoras.getValue();
                                    
            String mensaje  = "Sistema operativo "+sistemaOperativo;
            mensaje += "\n"+"Habilidades seleccionadas: "+habilidades;               
            mensaje += "\n"+"Horas que trabajas en computadora al día: "+ (String.valueOf(horas));
            
           JOptionPane.showMessageDialog(null, mensaje, "Encuesta",JOptionPane.INFORMATION_MESSAGE); 
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sldHorasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldHorasStateChanged
        // TODO add your handling code here:
        
            int horas = this.sldHoras.getValue();
            String mensaje = (String.valueOf(horas))+" horas";            
            this.lblSlider.setText(mensaje);        
    }//GEN-LAST:event_sldHorasStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAnalitico;
    private javax.swing.JCheckBox chkOrganizado;
    private javax.swing.JCheckBox chkProActivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblSlider;
    private javax.swing.JRadioButton rbdLinux;
    private javax.swing.JRadioButton rbdMac;
    private javax.swing.JRadioButton rbdWindows;
    private javax.swing.ButtonGroup rbdgSistemaOperativo;
    private javax.swing.JSlider sldHoras;
    // End of variables declaration//GEN-END:variables
}
